GET http://localhost:3000/blogs

###

GET http://localhost:3000/blogs/1

###

GET https://server-three-lac.vercel.app/login

###

POST https://server-three-lac.vercel.app/login

Content-Type: application/json

{
    "username": "madmaster",
    "password": "master"
}